const express = require("express")
const router = express.Router()
const tablas = require("./tabla")
const usuarios = require("./usuarios")
const alumnos = require("./alumnos")
const aulas = require("./aulas")
const ciclos = require("./ciclos")
const codigos = require("./codigos")
const cursos = require("./cursos")
const horas = require("./horas")
const roles = require("./roles")
const semanas = require("./semanas")
const clases = require("./clases")
const fechas = require("./fechas")
const modulos = require("./modulos") 
const ufs = require("./ufs")
const asistencia = require("./asistencias")
const clase_alumno = require("./clase_alumno")
const clases_curso = require("./clases_curso")
const horarios = require("./horarios")

//rutas

router.use("/tablas", tablas)
router.use("/usuarios", usuarios)
router.use("/alumnos", alumnos)
router.use("/aulas", aulas)
router.use("/ciclos", ciclos)
router.use("/codigos", codigos)
router.use("/cursos", cursos) 
router.use("/horas", horas)
router.use("/roles", roles)
router.use("/semanas", semanas)
router.use("/clases", clases)
router.use("/fechas", fechas)
router.use("/modulos", modulos)
router.use("/ufs", ufs)
router.use("/asistencias", asistencia)
router.use("/clase_alumno", clase_alumno)
router.use("/clases_curso", clases_curso)
router.use("/horarios", horarios)

router.get("/", (req, res)=>{
    res.send("estas en router")
})

module.exports = router